# Assignment 3

**Please follow the instructions. Do not add new cell! Write your code in designated areas.**

In [5]:
import datetime
import socket
import numpy as np

# Get local time
local_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# Get computer ID or hostname
computer_id = socket.gethostname()

# Print output with local time and computer ID
print('Assignment 3: Solutions by Aleksandr') # Please change your name here
print('Local Time:', local_time)
print('Computer ID:', computer_id)

Assignment 3: Solutions by Aleksandr
Local Time: 2023-07-11 21:29:15
Computer ID: DESKTOP-6GLOPD7


## NumPy

1. Create a 2D numpy array of size 4x5 with random integers between 1 and 10. Find the maximum value of the entire array. 


In [13]:
## Your code here down
arr_2d = np.random.randint(1, 10, size=(4,5))
print(arr_2d)
print(arr_2d.max())

# print(mean)
#print(std) and so on
## Your code here up

[[8 9 7 4 8]
 [4 3 7 6 8]
 [6 7 6 9 8]
 [9 1 5 4 8]]
9


2. Create a 1D numpy array of size 20 with random floats between 0 and 1. Reshape the array into a 4x5 matrix. Compute the mean of each row.

In [1]:
## Your code here down

# Create a 1D numpy array of size 20 with random floats between 0 and 1
random_array = np.random.rand(20)

# Reshape the array into a 4x5 matrix
matrix_4x5 = random_array.reshape(4, 5)

# Compute the mean of each row
row_means = np.mean(matrix_4x5, axis=1)

print("Original 1D array:")
print(random_array)

print("\nReshaped 4x5 matrix:")
print(matrix_4x5)

print("\nMean of each row:")
print(row_means)



## Your code here up

Original 1D array:
[0.10790618 0.73512598 0.559653   0.87917032 0.29408174 0.20054601
 0.24829216 0.91315133 0.86927837 0.52095311 0.17406205 0.30079038
 0.97849592 0.94407044 0.40750823 0.03935019 0.27340438 0.24236863
 0.41130929 0.61599066]

Reshaped 4x5 matrix:
[[0.10790618 0.73512598 0.559653   0.87917032 0.29408174]
 [0.20054601 0.24829216 0.91315133 0.86927837 0.52095311]
 [0.17406205 0.30079038 0.97849592 0.94407044 0.40750823]
 [0.03935019 0.27340438 0.24236863 0.41130929 0.61599066]]

Mean of each row:
[0.51518745 0.5504442  0.56098541 0.31648463]


3. Create a 2D numpy array of size 5x5 with random integers between 1 and 100. Compute standard deviation of each column.

In [2]:
## Your code here down

# Create a 2D numpy array of size 5x5 with random integers between 1 and 100
random_array = np.random.randint(1, 101, size=(5, 5))

# Compute the standard deviation of each column
column_std = np.std(random_array, axis=0)

print("Random 2D array:")
print(random_array)

print("\nStandard deviation of each column:")
print(column_std)

## Your code here up

Random 2D array:
[[ 29 100  14  69   1]
 [ 69  32  38  12  30]
 [ 90  47  51  14   2]
 [ 78  67  16  63  52]
 [ 80   6  11  57  13]]

Standard deviation of each column:
[21.17923511 31.8031445  15.73531061 24.79516082 19.27277873]


4. Create a 1D numpy array of size 15 with random floats between -10 and 10. Replace all negative values with their absolute values.

In [3]:
## Your code here down

# Create a 1D numpy array of size 15 with random floats between -10 and 10
random_array = np.random.uniform(-10, 10, size=15)

# Replace negative values with their absolute values
random_array = np.abs(random_array)

print("Original 1D array:")
print(random_array)

## Your code here up

Original 1D array:
[3.9443473  2.44945784 4.08038017 9.87909557 9.73998126 8.4281665
 2.39759892 8.65405515 1.40078077 6.91261835 3.58715161 7.1826152
 8.24980562 8.39548466 5.20023606]


5. Create a 2D numpy array of size 3x4 with random integers between 1 and 100. Calculate the sum of all elements in the array.

In [4]:
## Your code here down
# Create a 2D numpy array of size 3x4 with random integers between 1 and 100
random_array = np.random.randint(1, 101, size=(3, 4))

# Calculate the sum of all elements in the array
array_sum = np.sum(random_array)

print("Random 2D array:")
print(random_array)

print("\nSum of all elements in the array:", array_sum)

## Your code here up

Random 2D array:
[[36 63 18 18]
 [89  7 93 94]
 [11 66 47 81]]

Sum of all elements in the array: 623


7. Create a 2D numpy array of size 4x6 with random floats between 0 and 1. Normalize each column by subtracting the column mean and dividing by the column standard deviation.

In [5]:
## Your code here down
# Create a 2D numpy array of size 4x6 with random floats between 0 and 1
random_array = np.random.rand(4, 6)

# Calculate the column mean
column_mean = np.mean(random_array, axis=0)

# Calculate the column standard deviation
column_std = np.std(random_array, axis=0)

# Normalize each column by subtracting the column mean and dividing by the column standard deviation
normalized_array = (random_array - column_mean) / column_std

print("Original 2D array:")
print(random_array)

print("\nNormalized 2D array:")
print(normalized_array)

## Your code here up

Original 2D array:
[[0.53729542 0.16212528 0.20674118 0.42729683 0.193539   0.35301861]
 [0.49853133 0.69906814 0.22100492 0.40612911 0.53163234 0.27666699]
 [0.37671312 0.8643547  0.39416761 0.10186045 0.07887891 0.90371143]
 [0.46918144 0.31299791 0.47632358 0.42954375 0.26369918 0.08007308]]

Normalized 2D array:
[[ 1.12841098 -1.22645481 -1.02857414  0.62163403 -0.44095383 -0.16477945]
 [ 0.47423079  0.66855201 -0.90404907  0.46878606  1.59020271 -0.41465933]
 [-1.58156556  1.25189     0.60769322 -1.72827868 -1.12979494  1.63750104]
 [-0.02107622 -0.6939872   1.32492999  0.63785858 -0.01945393 -1.05806225]]


8. Create a 2D numpy array of size 10x10 with random integers between 1 and 100. Replace all values greater than 50 with 1 and all other values with 0.

In [6]:
## Your code here down
# Create a 2D numpy array of size 10x10 with random integers between 1 and 100
random_array = np.random.randint(1, 101, size=(10, 10))

# Replace all values greater than 50 with 1 and all other values with 0
binary_array = np.where(random_array > 50, 1, 0)

print("Random 2D array:")
print(random_array)

print("\nBinary 2D array:")
print(binary_array)

## Your code here up

Random 2D array:
[[ 58  11  51  16  62  40  34  21  98  14]
 [ 83  75  56 100   9  51  66  52  24  33]
 [100  63  43   1  26  62  94   9  79  86]
 [ 83  39  30  32  11  26  27  93  89  39]
 [ 41  72  80  18  83  22  20  61  49  79]
 [ 15  27  22  79  35  78  15  94  78  87]
 [  4  90  57  89  72  39  38  71  79  43]
 [ 96  48  33  41  58   6  29  91   8  45]
 [ 37  47  30  33  60  88  55  89  88  54]
 [ 17  14  94  52  11   1  88  89  46  21]]

Binary 2D array:
[[1 0 1 0 1 0 0 0 1 0]
 [1 1 1 1 0 1 1 1 0 0]
 [1 1 0 0 0 1 1 0 1 1]
 [1 0 0 0 0 0 0 1 1 0]
 [0 1 1 0 1 0 0 1 0 1]
 [0 0 0 1 0 1 0 1 1 1]
 [0 1 1 1 1 0 0 1 1 0]
 [1 0 0 0 1 0 0 1 0 0]
 [0 0 0 0 1 1 1 1 1 1]
 [0 0 1 1 0 0 1 1 0 0]]


9. Create a 1D numpy array of size 50 with random floats between 0 and 1. Find the number of elements greater than 0.5.

In [7]:
## Your code here down
# Create a 1D numpy array of size 50 with random floats between 0 and 1
random_array = np.random.rand(50)

# Find the number of elements greater than 0.5
count_greater_than_0_5 = np.sum(random_array > 0.5)

print("Random 1D array:")
print(random_array)

print("\nNumber of elements greater than 0.5:", count_greater_than_0_5)

## Your code here up

Random 1D array:
[0.06991865 0.08696968 0.87816841 0.25787145 0.79024154 0.20483553
 0.66081863 0.22166936 0.20940846 0.06237691 0.71289085 0.74944469
 0.55305413 0.68880192 0.4155187  0.05125838 0.9062521  0.5221314
 0.72742169 0.76743689 0.09589138 0.60114702 0.0139306  0.59965475
 0.73681752 0.4770122  0.9535965  0.15304772 0.52539743 0.23270683
 0.40558067 0.10076812 0.30419463 0.93162198 0.36661355 0.61215554
 0.43046638 0.12673246 0.61141757 0.68352781 0.01424094 0.17375111
 0.32569462 0.59724961 0.96110136 0.82670889 0.12228831 0.81282719
 0.65759334 0.38505276]

Number of elements greater than 0.5: 25


10. Create a 2D numpy array of size 5x5 with random floats between -1 and 1. Find the absolute difference between the maximum and minimum values in each row.

In [8]:
## Your code here down
# Create a 2D numpy array of size 5x5 with random floats between -1 and 1
random_array = np.random.uniform(-1, 1, size=(5, 5))

# Find the absolute difference between the maximum and minimum values in each row
row_abs_diff = np.abs(np.max(random_array, axis=1) - np.min(random_array, axis=1))

print("Random 2D array:")
print(random_array)

print("\nAbsolute difference between max and min values in each row:")
print(row_abs_diff)


## Your code here up

Random 2D array:
[[ 0.12794816 -0.8773968   0.29477031  0.24921248  0.13271497]
 [ 0.56485811 -0.66559805  0.24587446 -0.56928892 -0.81181819]
 [-0.30296512  0.84805236 -0.76844947  0.18636431  0.32590045]
 [ 0.41842787  0.87086326  0.89981133  0.25822795 -0.24830375]
 [ 0.44546654  0.63586015 -0.00532505  0.19166966 -0.6211888 ]]

Absolute difference between max and min values in each row:
[1.17216711 1.3766763  1.61650183 1.14811508 1.25704896]


## Pandas

Please refer the dataframe (farm data) we have created in the training. Please copy that cell and paste it below before starting this part. 

In [11]:
import random
import pandas as pd

# Define the range for longitude and latitude
lon_range = (-105, -100)
lat_range = (50, 52)

# Define the list of soil types
soil_types = ['black', 'gray', 'dark brown', 'brown', None]

# Create an empty list to store the farms
farms = []

# Generate 40 farms
for i in range(40):
    farm = {
        'farm_name': f'Farm {i+1}', # f is formated string
        'farm_lon': round(random.uniform(lon_range[0], lon_range[1]), 2), # random lon with 2 decimal points
        'farm_lat': round(random.uniform(lat_range[0], lat_range[1]), 2), # rantom lat with 2 decimal points
        'temperature': round(random.uniform(18, 25), 1), #random temp with 1 decimal points
        'precipitation': round(random.uniform(20, 50), 1), # random prec with 1 decimal points
        'soil_type': random.choice(soil_types) # random soil types from above list
    }
    farms.append(farm)

In [12]:
df = pd.DataFrame(farms)# your code here

1. Select the rows where the temperature is above 20 degrees Celsius.

In [13]:
## Your code here down
# Select the rows where the temperature is above 20 degrees Celsius
selected_rows = df[df['temperature'] > 20]

print(selected_rows)

## Your code here up

   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
0     Farm 1   -100.66     50.10         23.1           46.3       brown
3     Farm 4   -101.96     51.49         21.9           32.0       black
4     Farm 5   -104.31     50.20         23.5           22.8        None
5     Farm 6   -102.44     50.05         20.6           36.5        gray
6     Farm 7   -100.80     50.35         21.9           49.2  dark brown
7     Farm 8   -100.98     50.16         20.2           27.5  dark brown
8     Farm 9   -103.55     51.08         22.2           38.5        gray
9    Farm 10   -101.88     51.79         21.7           35.1       black
11   Farm 12   -104.51     50.22         22.6           38.3       black
12   Farm 13   -100.79     51.74         22.8           46.9  dark brown
13   Farm 14   -102.94     51.65         20.3           29.8        gray
14   Farm 15   -100.46     51.36         20.4           49.5       brown
16   Farm 17   -100.80     50.94         21.5      

2. Sort the DataFrame by precipitation in descending order.

In [14]:
## Your code here down
# Sort the DataFrame by precipitation in descending order
sorted_df = df.sort_values(by='precipitation', ascending=False)

print(sorted_df)


## Your code here up

   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
16   Farm 17   -100.80     50.94         21.5           49.7       black
14   Farm 15   -100.46     51.36         20.4           49.5       brown
6     Farm 7   -100.80     50.35         21.9           49.2  dark brown
29   Farm 30   -101.80     51.29         24.4           48.6       black
32   Farm 33   -100.71     51.36         20.8           47.5  dark brown
30   Farm 31   -101.76     50.47         21.5           47.2        gray
12   Farm 13   -100.79     51.74         22.8           46.9  dark brown
0     Farm 1   -100.66     50.10         23.1           46.3       brown
15   Farm 16   -104.91     50.66         19.2           45.7        gray
39   Farm 40   -102.48     50.88         24.0           39.5        None
8     Farm 9   -103.55     51.08         22.2           38.5        gray
11   Farm 12   -104.51     50.22         22.6           38.3       black
33   Farm 34   -104.45     50.76         24.8      

3. Filter the DataFrame to include only the farms located within latitude (51.15 & 51.00) range.

In [15]:
## Your code here down
# Filter the DataFrame to include only the farms within latitude range (51.00, 51.15)
filtered_df = df[(df['farm_lat'] >= 51.00) & (df['farm_lat'] <= 51.15)]

print(filtered_df)

## Your code here up

   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
8     Farm 9   -103.55     51.08         22.2           38.5        gray
36   Farm 37   -102.76     51.11         23.2           34.5  dark brown
37   Farm 38   -104.53     51.13         18.6           22.9  dark brown


 4. Calculate the standard deviation of precipitation for each soil type.

In [16]:
## Your code here down
# Calculate the standard deviation of precipitation for each soil type
std_dev_by_soil_type = df.groupby('soil_type')['precipitation'].std()

print(std_dev_by_soil_type)

## Your code here up

soil_type
black         10.458617
brown          8.161852
dark brown    10.463121
gray           7.367881
Name: precipitation, dtype: float64


5. Calculate the cumulative sum of precipitation for each soil type.

In [18]:
## Your code here down
# Calculate the cumulative sum of precipitation for each soil type
cumulative_sum_by_soil_type = df.groupby('soil_type')['precipitation'].cumsum()

# Add the cumulative sum as a new column in the DataFrame
df['cumulative_sum_precipitation'] = cumulative_sum_by_soil_type

print(df)

## Your code here up

   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type  \
0     Farm 1   -100.66     50.10         23.1           46.3       brown   
1     Farm 2   -100.57     51.40         19.0           22.7       black   
2     Farm 3   -104.63     50.94         19.1           33.8  dark brown   
3     Farm 4   -101.96     51.49         21.9           32.0       black   
4     Farm 5   -104.31     50.20         23.5           22.8        None   
5     Farm 6   -102.44     50.05         20.6           36.5        gray   
6     Farm 7   -100.80     50.35         21.9           49.2  dark brown   
7     Farm 8   -100.98     50.16         20.2           27.5  dark brown   
8     Farm 9   -103.55     51.08         22.2           38.5        gray   
9    Farm 10   -101.88     51.79         21.7           35.1       black   
10   Farm 11   -103.38     51.17         19.5           33.7       brown   
11   Farm 12   -104.51     50.22         22.6           38.3       black   
12   Farm 13

6. Determine the top 3 farms with the highest average temperature.

In [19]:
## Your code here down
# Group by farm_name and calculate the average temperature for each farm
average_temp_by_farm = df.groupby('farm_name')['temperature'].mean()

# Sort farms based on average temperature in descending order
sorted_farms = average_temp_by_farm.sort_values(ascending=False)

# Select the top 3 farms with the highest average temperature
top_3_farms = sorted_farms.head(3)

print(top_3_farms)


## Your code here up

farm_name
Farm 26    24.8
Farm 34    24.8
Farm 30    24.4
Name: temperature, dtype: float64


7. Find famrs in each soil type that have the highest temperature.

In [20]:
## Your code here down
# Group by soil_type and find the maximum temperature for each group
max_temp_by_soil_type = df.groupby('soil_type')['temperature'].max()

# Filter the original DataFrame to select the farms with the highest temperature in each soil type
farms_with_highest_temp_by_soil_type = df.loc[df.groupby('soil_type')['temperature'].idxmax()]

print(farms_with_highest_temp_by_soil_type)

## Your code here up

   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type  \
33   Farm 34   -104.45     50.76         24.8           37.5       black   
0     Farm 1   -100.66     50.10         23.1           46.3       brown   
36   Farm 37   -102.76     51.11         23.2           34.5  dark brown   
27   Farm 28   -103.61     50.08         23.1           30.4        gray   

    cumulative_sum_precipitation  
33                         285.1  
0                           46.3  
36                         351.2  
27                         180.9  


8. Create new column 'percentage_tot_prec' and add the percentage contribution of each farm's precipitation (relative to total precipitation) to the column.

In [21]:
## Your code here down
# Calculate the total precipitation
total_precipitation = df['precipitation'].sum()

# Calculate the percentage contribution of each farm's precipitation relative to the total precipitation
df['percentage_tot_prec'] = (df['precipitation'] / total_precipitation) * 100

print(df)


## Your code here up

   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type  \
0     Farm 1   -100.66     50.10         23.1           46.3       brown   
1     Farm 2   -100.57     51.40         19.0           22.7       black   
2     Farm 3   -104.63     50.94         19.1           33.8  dark brown   
3     Farm 4   -101.96     51.49         21.9           32.0       black   
4     Farm 5   -104.31     50.20         23.5           22.8        None   
5     Farm 6   -102.44     50.05         20.6           36.5        gray   
6     Farm 7   -100.80     50.35         21.9           49.2  dark brown   
7     Farm 8   -100.98     50.16         20.2           27.5  dark brown   
8     Farm 9   -103.55     51.08         22.2           38.5        gray   
9    Farm 10   -101.88     51.79         21.7           35.1       black   
10   Farm 11   -103.38     51.17         19.5           33.7       brown   
11   Farm 12   -104.51     50.22         22.6           38.3       black   
12   Farm 13

9. Create a new column called "precipitation_rank" that ranks the farms based on their precipitation in ascending order, with ties being assigned the same rank.

In [22]:
## Your code here down
# Create a new column "precipitation_rank" based on the rank of precipitation in ascending order
df['precipitation_rank'] = df['precipitation'].rank(ascending=True, method='average')

print(df)

## Your code here up

   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type  \
0     Farm 1   -100.66     50.10         23.1           46.3       brown   
1     Farm 2   -100.57     51.40         19.0           22.7       black   
2     Farm 3   -104.63     50.94         19.1           33.8  dark brown   
3     Farm 4   -101.96     51.49         21.9           32.0       black   
4     Farm 5   -104.31     50.20         23.5           22.8        None   
5     Farm 6   -102.44     50.05         20.6           36.5        gray   
6     Farm 7   -100.80     50.35         21.9           49.2  dark brown   
7     Farm 8   -100.98     50.16         20.2           27.5  dark brown   
8     Farm 9   -103.55     51.08         22.2           38.5        gray   
9    Farm 10   -101.88     51.79         21.7           35.1       black   
10   Farm 11   -103.38     51.17         19.5           33.7       brown   
11   Farm 12   -104.51     50.22         22.6           38.3       black   
12   Farm 13

10. Normalize the temperature column to a range between 0 and 1 for each farm.

In [23]:
## Your code here down
# Normalize the temperature column to a range between 0 and 1 for each farm
min_temp = df['temperature'].min()
max_temp = df['temperature'].max()
df['normalized_temperature'] = (df['temperature'] - min_temp) / (max_temp - min_temp)

print(df)


## Your code here up

   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type  \
0     Farm 1   -100.66     50.10         23.1           46.3       brown   
1     Farm 2   -100.57     51.40         19.0           22.7       black   
2     Farm 3   -104.63     50.94         19.1           33.8  dark brown   
3     Farm 4   -101.96     51.49         21.9           32.0       black   
4     Farm 5   -104.31     50.20         23.5           22.8        None   
5     Farm 6   -102.44     50.05         20.6           36.5        gray   
6     Farm 7   -100.80     50.35         21.9           49.2  dark brown   
7     Farm 8   -100.98     50.16         20.2           27.5  dark brown   
8     Farm 9   -103.55     51.08         22.2           38.5        gray   
9    Farm 10   -101.88     51.79         21.7           35.1       black   
10   Farm 11   -103.38     51.17         19.5           33.7       brown   
11   Farm 12   -104.51     50.22         22.6           38.3       black   
12   Farm 13